apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: spring-boot-examples
  name: spring-rest-sales
  labels:
    app: spring-rest-sales
spec:
  replicas: 1
  template:
    metadata:
      name: spring-rest-sales
      labels:
        app: spring-rest-sales
    spec:
      containers:
        - name: spring-rest-sales
          image: harilearning1989/spring-rest-sales:2
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: spring-rest-sales
