apiVersion: v1
kind: Service
metadata:
  name: spring-rest-sales
spec:
  ports:
    - name: spring-rest-sales
      port: 8082
      protocol: TCP
      targetPort: 8082
  selector:
    app: spring-rest-sales
  type: ClusterIP